In [5]:
import numpy as np

In [2]:
a = [[1,2,3],[4,5,6],[7,8,9]]
a

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
b = np.array(a)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
c = np.array([[1,2,3],[3,4,5],[4,5,6]])
c

array([[1, 2, 3],
       [3, 4, 5],
       [4, 5, 6]])

In [9]:
e = b.dot(c)
e

array([[ 19,  25,  31],
       [ 43,  58,  73],
       [ 67,  91, 115]])

In [17]:
f = np.where(e<20, e, 10*e)
f

array([[  19,  250,  310],
       [ 430,  580,  730],
       [ 670,  910, 1150]])