In [1]:

import numpy as np

In [4]:
a = np.arange(0,15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [5]:
a[2:6]


array([2, 3, 4, 5])

In [7]:
a[1:5] = 50
a

array([ 0, 50, 50, 50, 50,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [8]:
b = a[0:4]
b

array([ 0, 50, 50, 50])

In [9]:
b[:] = 91
b

array([91, 91, 91, 91])

In [11]:
a

array([91, 91, 91, 91, 50,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [12]:
c = a.copy()
c

array([91, 91, 91, 91, 50,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [13]:
a_m = np.array([[3,4,1],[1,4,5],[6,9,5]])
a_m


array([[3, 4, 1],
       [1, 4, 5],
       [6, 9, 5]])

In [23]:
a_m[0:2,1:]

array([[4, 1],
       [4, 5]])

In [25]:
b = np.zeros((10,10))
b

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])